### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by jim-rosales** [monikarackauskaite/bwui-capstone-placeholder#6]
You have a couple syntax issues here like a missing opening `{` and it seems like you wrote `ing` instead of `img`

```CSS
@media only screen and (max-width: 300px) {
  .image-container {
    margin-top: 10px;
    margin-bottom: 20px;
  }
  .search-bar {
    margin-top: 10px;
    margin-bottom: 20px;
  }
  .cart {
    max-width: 70px;;
  }
  img: border-box;
  }
}
```

https://github.com/monikarackauskaite/bwui-capstone-placeholder/blob/612f288c66fe15c1b2163d424cae1cab01843d53/Monika-Rackauskaite_ware-house-starting-code/resources/css/base.css#L180-L194
